import Head from 'next/head';
import Header from '../components/header';
import Nav from '../components/nav';
import Banner from '../components/banner'

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={''}>
          <Header />
          <Banner />
          <Nav />
      </main>

      <footer className={''}>

      </footer>
    </div>
  )
}
